### ISSUE TITLE
multi-db mode

### ISSUE THREAD

**Issue by DrorSegev** [jonathanpotts/docker-babelfishpg#1]
Can you elaborate how to run the container in multi-db migration mode?

Dror

**Comment by jonathanpotts** [comment]
For reference: [Migration Mode in README.md](https://github.com/jonathanpotts/docker-babelfishpg/blob/main/README.md#migration-mode)

If you append `-m multi-db` to the `docker run -d -p 1433:1433 jonathanpotts/babelfishpg` command used to create the container, it will be setup in multi-db mode (e.g. `docker run -d -p 1433:1433 jonathanpotts/babelfishpg -m multi-db`).

You can then connect to the database, and use the following query to create a database (in this example, named `exampledb`):

```tsql
CREATE DATABASE exampledb
```

You can use the following query to see the databases:

```tsql
SELECT name, database_id, create_date  
FROM sys.databases
```
