### ISSUE TITLE
postgis extension

### ISSUE THREAD

**Issue by bachpro900** [jonathanpotts/docker-babelfishpg#11]
```
ERROR:  Could not open extension control file "/opt/babelfish/share/postgresql/extension/postgis.control": No such file or directory.extension "postgis" is not available 

ERROR:  extension "postgis" is not available
```

Got this error when trying to install the PostGIS extension. Is there a way to add the extension to an existing container **(BABEL_3_2_0__PG_15_3)** ? Thanks for your support.

**Comment by jonathanpotts** [comment]
Adding other extensions is outside of the scope of this project.

As a one-time courtesy, I have made commit fcead065012d56e41137c7a140f2b6a944bf372d on a separate branch that includes the PostGIS extension.

To build an image using the commit, use:
```
docker build -t jonathanpotts/babelfishpg:postgis https://github.com/jonathanpotts/docker-babelfishpg.git#fcead065012d56e41137c7a140f2b6a944bf372d --build-arg BABELFISH_VERSION=BABEL_3_2_0__PG_15_3 --build-arg POSTGIS_VERSION=3.4.1
```

Afterwards, you can start a container with the new image using:
```
docker run -d -p 1433:1433 -p 5432:5432 jonathanpotts/babelfishpg:postgis
```

You can view the commit to see what changes were made that you can apply to modified versions you may have.

It is non-trivial to add PostGIS to an already running container, so your best bet would be to move the data over to a container running an image that has PostGIS included and then run:
```sql
CREATE EXTENSION postgis;
```

**Comment by bachpro900** [comment]
Thank you. Worked perfectly.
