### ISSUE TITLE
Update for 15.4 and Bablefish 3.3.0

### ISSUE THREAD

**Issue by edencorbin** [jonathanpotts/docker-babelfishpg#12]
Any interest in updating this for the latest bablefish support?

**Comment by jonathanpotts** [comment]
I have pushed PostgreSQL 15.4 with Babelfish 3.3.0 to the Docker Hub repository and created a workflow. This automated process updates the Docker Hub image within a day of a new release, as long as no breaking changes are introduced to the build process.
