### ISSUE TITLE
SSMS connection issue

### ISSUE THREAD

**Issue by bobtheman** [jonathanpotts/docker-babelfishpg#2]
TITLE: Cannot connect to server error message using SSMS v18
------------------------------

Cannot connect to localhost,1433.

------------------------------
ADDITIONAL INFORMATION:

Specified cast is not valid. (Microsoft.SqlServer.ConnectionInfo)

Using the username and password supplied

![image](https://user-images.githubusercontent.com/7711495/190656049-8eeea4dd-3a37-4d20-88b9-dc64ac3ae4db.png)

**Comment by jonathanpotts** [comment]
This Docker image was made with the original release of Babelfish for PostgreSQL which has very limited support for SSMS. I will look into updating to the newest version which should add more SSMS support.

**Comment by jonathanpotts** [comment]
OK, the Docker image has been updated to Babelfish 2.1.1 which has additional support for SSMS. The support is still limited, but you should be able to login with the Object Explorer now. If you pull the latest image then it should work.

You can create a new container using the latest image using the following command:

`docker run -d -p 1433:1433 jonathanpotts/babelfishpg:latest`

**Comment by bobtheman** [comment]
Hi, just to confirm that resolved the issue, i can now login using SSMS, thanks for the help and nice work

![image](https://user-images.githubusercontent.com/7711495/190844464-6c4fec67-ed58-4923-8c0e-3435231b0f84.png)

**Comment by bobtheman** [comment]
Hi, is it possible to still connect using PGAdmin as well as SSMS?

**Comment by jonathanpotts** [comment]
I think you should be able to as long as you map the the port (5432) for the Docker container.

**Comment by bobtheman** [comment]
Hi, yeah that worked great, thanks for the help,

if anyone else needs to do this

docker run --name your-container-name -d -p 1433:1433 -p 5432:5432 jonathanpotts/babelfishpg:latest -u babelfish_user -p 12345678

PG Admin
Host: host.docker.internal
Port: 5432

SSMS
localhost,1433
