### ISSUE TITLE
Update to version 2.2

### ISSUE THREAD

**Issue by alexandre-henzen** [jonathanpotts/docker-babelfishpg#3]
Hi, could you update the Babelfish image to version 2.2?
I tried to build the DockerFile but occur this error:
hown: cannot access '/data/babelfish': No such file or directory
The command '/bin/sh -c chown postgres ${BABELFISH_DATA}' returned a non-zero code: 1

Regards

**Comment by jonathanpotts** [comment]
Done with 5150938de395ad58e0363a2d5f3a30d5623b0412. It is also on Docker Hub via the `jonathanpotts/babelfishpg:2.2.0` or `jonathanpotts/babelfishpg:latest` image.
