### ISSUE TITLE
Error running image after building dockerfile

### ISSUE THREAD

**Issue by calmitchell617** [jonathanpotts/docker-babelfishpg#4]
Hi Jonathan, thanks for making this repository. I can tell you put a lot of thought into it.

I'm having trouble running a container after building the Dockerfile myself. For example, I ran the following command to build on Ubuntu 20.04:

```
docker build -t babelfish:2.2.1 . --build-arg BABELFISH_VERSION=BABEL_2_2_1__PG_14_5
```

And then try to run with:

```
docker run babelfish:2.2.1
```

However, I get the following error:

```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/start.sh": permission denied: unknown.
```

I'm not sure if your warning about CRLF vs LF in the `start.sh` script applies to me, since this is on Linux, but I checked anyways, and it seems like the script has LF:

```
cat -A start.sh

#!/bin/sh$
BABELFISH_HOME=/opt/babelfish$
BABELFISH_DATA=/data/babelfish$
$
cd ${BABELFISH_HOME}/bin$
$
# Set default argument values$
```

Do you have any guidance on how to overcome this error?

**Comment by calmitchell617** [comment]
UPDATE.

I spent half an hour debugging, got frustrated, wrote this issue, then tried one last thing, and it worked.

On Ubuntu host:
```
chmod +x start.sh
```

BEFORE building. Now it runs.

**Comment by jonathanpotts** [comment]
Thanks for letting me know the resolution. I updated the readme with your guidance.
