### ISSUE TITLE
Problem when trying to connect from SSMS

### ISSUE THREAD

**Issue by Ghyath-Serhal** [jonathanpotts/docker-babelfishpg#5]
I am trying to run this image on my machine.
Note that on my machine sql server is installed on the default port 1433.

I have installed the image on docker.
I run the container using the below command
**docker run -d -p 1433:1444 jonathanpotts/babelfishpg**

below image is the result of: **docker container ls**

![2023_02_16_15_33_03_Window](https://user-images.githubusercontent.com/6513173/219379550-bac6f0a9-e8f4-4b11-987f-75fbfd4fa036.png)

When trying to connect using **SSMS** on port **5432**, I am getting the below error.

![ssms](https://user-images.githubusercontent.com/6513173/219380015-5479beb1-4eda-457e-828c-e202b3ecd172.png)

When trying to connect using **SSMS** on port **1444**, I am getting the below error.
![ssms1](https://user-images.githubusercontent.com/6513173/219384978-512c58c7-fe07-4fb7-80bf-10ea26678a05.png)

**Comment by jonathanpotts** [comment]
You have the port numbers reversed in your run command. The first number is the port published to the host and the second number is the port of the service running inside the container. Also, port 5432 is not accessible to the host with the standard command and would only be used for Postgres if it was.

The command you should use is (assuming you want it accessible on port 1444):
`docker run -d -p 1444:1433 jonathanpotts/babelfishpg`

```
CONTAINER ID   IMAGE                       COMMAND       CREATED          STATUS          PORTS                              NAMES
f7105d7141d5   jonathanpotts/babelfishpg   "/start.sh"   13 seconds ago   Up 12 seconds   5432/tcp, 0.0.0.0:1444->1433/tcp   exciting_varahamihira
```

![image](https://user-images.githubusercontent.com/17758200/219389600-84fd356f-0467-4714-87c2-13e4ac9cc06f.png)
